version: '3'

services:
  vapor:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_LISTEN=0.0.0.0
      - SERVER_PORT=8080
      - MYSQL_HOSTNAME=db
      - MYSQL_USER=mentor
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=mentor
    volumes:
      - ./Public:/vapor/Public:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_USER=mentor
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=mentor
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:

networks:
    default:
    internal:
        internal: true
