version: '3'

services:
  vapor:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - SERVER_LISTEN=0.0.0.0
      - SERVER_PORT=8888
      - MYSQL_HOSTNAME=db
      - MYSQL_USER=mentor
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=mentor
      - REDIS_HOSTNAME=cache
    volumes:
      - ./Public:/vapor/Public:ro
      - ./Resources:/vapor/Resources:ro
    depends_on:
      - db
    networks:
        default:
        internal:
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_USER=mentor
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=mentor
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
  
  cache:
    image: redis:4
    restart: always
    volumes:
      - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true
